'use strict'

module.exports = {
  NODE_ENV: '"production"',
  AZURE_FUNCTIONS_API_ENDPOINT: '""',
  AZURE_FUNCTIONS_API_KEY: '""',
  AZURE_FUNCTIONS_AD_APPLICATION_ID: '""',
  AZURE_FUNCTIONS_ADMIN_API_ENDPOINT: '""',
  AZURE_FUNCTIONS_ADMIN_API_KEY: '""',
  AZURE_FUNCTIONS_ADMIN_AD_APPLICATION_ID: '""',
  LOGOUT_REDIRECT_URL: '""'
}
